- hosts: authoirzed
  tasks:
  - name: Set authorized key took from file
    authorized_key:
      user: oracle
      state: present
      key: "{{ lookup('file','/opt/jenkins_original/oracle_credit_prod.pem') }}"
      path: /home/oracle/authorized_keys

